version: "3.8"

services:
   
  eurkaserver:
    container_name: eurkaserver 
    image: eurkaserver
    build: ./eurkaserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - medicalClininc
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
        
  postgresqldb:
    container_name: postgresqldb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=medicalClinic
    restart: always
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - medicalClininc
      
  medicalclinc:
    container_name: medicalclinc 
    image: medicalclinc
    build: ./medicalClinc
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - medicalClininc
    depends_on:
      - eurkaserver
      - postgresqldb

    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://localhost:5432/medicalClinic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      
volumes:
  local_pgdata:
  
networks:
  medicalClininc: