version: "3.8"

services:
   
  eurkaserver:
    container_name: eurkaserver 
    image: eurkaserver
    build: ./eurkaserver
    mem_limit: 700m
    
    ports:
      - "8070:8070"
      
    networks:
      - backend
 
    environment:
      EUREKA_SERVER: "http://eurkaserver:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      
  db:
    image: db
    container_name: db
    build:
      context: ./db
      target: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=medicalclinc
      
    ports:
      - 5432:5432
      
    networks:
      - backend

  medicalclinc:
    image: medicalclinc
    container_name: medicalclinc 
    build: ./medicalClinc
    mem_limit: 700m
    
    ports:
      - "8089:8089"

    depends_on:
      - eurkaserver
      - db

    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
        window: 120s
        
    environment:
      EUREKA_SERVER: "http://eurkaserver:8070/eureka/"
      DB_URL: "r2dbc:postgresql://db:5432/medicalclinc"
      
    networks:
      - backend
      
networks:
  backend:
